version: '3.8'
services:

  db:
    image: postgres:13.9-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: nezhinsky/foodgram-project-backend:latest
#    build:
#      context: ../backend
#      dockerfile: Dockerfile
    command: >
      bash -c "gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - data_value:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
      - docs:/app/docs/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: nezhinsky/foodgram-project-react:latest
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - docs:/usr/share/nginx/html/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:
  docs: